import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/providers/theme.provider';
import { AppProviders } from '@/providers/app.provider';
import { NavBar } from '@/app/_components/nav-bar.component';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <AppProviders>
          <NavBar className="mx-12 my-3" />

          {children}
        </AppProviders>
      </body>
    </html>
  );
}
